CREATE SCHEMA IF NOT EXISTS ARQUIVOS;

CREATE TABLE ARQUIVOS.TB_ARQUIVO
(
    COD_ARQUIVO      BIGSERIAL   NOT NULL,
    TXT_CONTENT_TYPE VARCHAR(50) NOT NULL,
    TXT_NOME_ARQUIVO VARCHAR     NOT NULL,
    NUM_TAMANHO      int4        NOT NULL,
    DTH_UPLOAD       timestamp   NOT NULL,
    CONSTRAINT PK_ARQUIVO PRIMARY KEY (COD_ARQUIVO)
);