CREATE SCHEMA ARQUIVOS;
CREATE TABLE ARQUIVOS.TB_ARQUIVO
(
    COD_ARQUIVO      INT4 PRIMARY KEY,
    TXT_CONTENT_TYPE TEXT      NOT NULL,
    TXT_NOME_ARQUIVO TEXT      NOT NULL,
    NUM_TAMANHO      INT       NOT NULL,
    DTH_UPLOAD       TIMESTAMP NOT NULL
);

CREATE SEQUENCE ARQUIVOS.TB_ARQUIVO_COD_ARQUIVO_SEQ;