CREATE SCHEMA ARQUIVOS;
CREATE TABLE ARQUIVOS.TB_TIPO_ARQUIVO
(
    COD_TIPO_ARQUIVO          INT4 PRIMARY KEY,
    TXT_DESCRICAO             TEXT,
    TXT_CAMINHO_ARMAZENAMENTO TEXT,
    TXT_CONTENT_TYPE          TEXT
);

CREATE TABLE ARQUIVOS.TB_ARQUIVO
(
    COD_ARQUIVO      INT4 PRIMARY KEY,
    TXT_CONTENT_TYPE TEXT      NOT NULL,
    TXT_NOME_ARQUIVO TEXT      NOT NULL,
    NUM_TAMANHO      INT       NOT NULL,
    DTH_UPLOAD       TIMESTAMP NOT NULL,
    COD_TIPO_ARQUIVO INT       NOT NULL,
    CONSTRAINT FK_TB_ARQUIVO_COD_TIPO_ARQUIVO FOREIGN KEY (COD_TIPO_ARQUIVO) REFERENCES ARQUIVOS.TB_TIPO_ARQUIVO (COD_TIPO_ARQUIVO)
);

CREATE SEQUENCE ARQUIVOS.TB_ARQUIVO_COD_ARQUIVO_SEQ;
CREATE SEQUENCE ARQUIVOS.TB_TIPO_ARQUIVO_COD_TIPO_ARQUIVO_SEQ;